### ISSUE TITLE
Strange stack overflow

### ISSUE THREAD

**Issue by Kerollmops** [rustasync/runtime#44]
I was trying a little bit this cool crate and wanted to use sled in it. When I tried to open the database in the main I faced a stack overflow.

```toml
[package]
name = "runtime-sled"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
runtime = "0.3.0-alpha.3"
sled = "0.24.1"
```

```rust
#[runtime::main]
async fn main() -> Result<(), failure::Error> {
    let database = sled::Db::start_default("my-db")?;
    Ok(())
}
```

I ran `rust-lldb` and do not found anything strange.

EDIT: I found out that it is probably related to my work on making sled async. I lied, I did not used sled 0.24.1 but a custom version of mine.

The patch that I applied on sled is here, I do not understand what could make a stack overflow.
https://github.com/spacejam/sled/commit/a4db47b3504c222dfbe6a006e2e6dcbf66fb4d44
